"
A ShBadgesAppTest is a test class for testing the behavior of ShBadgesApp
"
Class {
	#name : #ShBadgesAppTest,
	#superclass : #TestCase,
	#category : #'Badges-Tests-UI'
}

{ #category : #test }
ShBadgesAppTest >> testBadgeUserVariables [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
ShBadgesAppTest >> testBadgeUserVariablesAt [

	self flag: #toImplement.
	self assert: false
]
